apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-api-deployment
spec:
  selector:
    matchLabels:
      app: cars-island
  replicas: 3
  template:
    metadata:
      labels:
        app: cars-island
    spec:
      containers:
        - name: cars-api
          image: acrcarsislandd01/cars-island-web-api:cars-web-api-0.1.60
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 300m
              memory: "100Mi"
            requests:
              cpu: 100m
              memory: "50Mi"
          env:
            - name: CosmosConnectionString
              valueFrom:
                configMapKeyRef:
                  name: cars-configmap
                  key: CosmosConnectionString

            - name: BlobAccountName
              valueFrom:
                configMapKeyRef:
                  name: cars-configmap
                  key: BlobAccountName

            - name: BlobKey
              valueFrom:
                configMapKeyRef:
                  name: cars-configmap
                  key: BlobKey

            - name: BlobContainerName
              valueFrom:
                configMapKeyRef:
                  name: cars-configmap
                  key: BlobContainerName

            - name: BlobConnectionString
              valueFrom:
                configMapKeyRef:
                  name: cars-configmap
                  key: BlobConnectionString
---
kind: Service
apiVersion: v1
metadata:
  name: cars-api-service
spec:
  selector:
    app: cars-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer #NodePort
